In [35]:
import pandas as pd

In [38]:
data =pd.read_csv("housing.csv")
data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [21]:
data.drop(["ocean_proximity","total_bedrooms"], axis=1 , inplace = True)

In [22]:
data.isna().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

In [23]:
data.duplicated().sum()

np.int64(0)

In [24]:
X=data.drop(["median_house_value"], axis = 1)
y= data.median_house_value

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [27]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((15480, 7), (5160, 7), (15480,), (5160,))

In [28]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [31]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
y_pred_train = model.predict(X_train)

acc = r2_score(y_train, y_pred_train)
print("Accuracy:", acc)

mae = mean_absolute_error(y_train, y_pred_train)
print("Mean Absolute Error:", mae)

Accuracy: 0.6322170945985652
Mean Absolute Error: 51246.12898423676

In [32]:
y_pred_test=model.predict(X_test)

r2_score(y_test, y_pred_test)

0.6326905102474192

In [34]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly = PolynomialFeatures(degree=2)
X_poly_train = poly.fit_transform(X_train)

poly.fit(X_poly_train, y_train)
lin2 = LinearRegression()
lin2.fit(X_poly_train, y_train)

LinearRegression()

In [40]:
lin2.score(poly.fit_transform(X_train), y_train)

0.6911574942398366