In [35]:
import pandas as pd

In [36]:
data = pd.read_csv("/content/data.csv")

In [37]:
data.isna().sum()

male                 0
age                  0
education          105
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64

In [38]:
data.dropna(inplace=True)

In [39]:
data.isna().sum()

male               0
age                0
education          0
currentSmoker      0
cigsPerDay         0
BPMeds             0
prevalentStroke    0
prevalentHyp       0
diabetes           0
totChol            0
sysBP              0
diaBP              0
BMI                0
heartRate          0
glucose            0
TenYearCHD         0
dtype: int64

In [40]:
data.duplicated().sum()

np.int64(0)

In [41]:
data.select_dtypes("O")

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 16, 17, 18, 19, 20, 22, 23, 24, 25, 27, 28, 29, 30, 31, 32, 34, 35, 37, 38, 39, 40, 41, 43, 44, 45, 46, 47, 48, 50, 51, 52, 53, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 71, 73, 74, 75, 76, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 112, ...]

[3656 rows x 0 columns]

In [42]:
x= data.drop(["TenYearCHD"], axis= 1)
y= data.TenYearCHD

In [43]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(x,y, test_size=0.25, random_state=42)

In [44]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((2742, 15), (2742,), (914, 15), (914,))

In [45]:
import warnings
warnings.filterwarnings("ignore")

In [46]:
from sklearn.linear_model import LogisticRegression

In [47]:
lr = LogisticRegression()

In [48]:
lr.fit(X_train, y_train)

LogisticRegression()

In [49]:
y_train_pred = lr.predict(X_train)

In [50]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [52]:
confusion_matrix(y_train, y_train_pred)

array([[2312,   15],
       [ 399,   16]])

In [53]:
accuracy_score(y_train, y_train_pred)

0.849015317286652

In [ ]:
model ne preict 1 kia  aur True hogia actual1 tha   ---- >   TP
model  ne predict 0 kia aur true hogia actual 0 tha   - ---->    TN
model nai preict 1 kia aur aur false bol kr actual mai false hopga ----- FP
model nai predict kia 0 aur false bol kr actual mai 1 tha      _____>    FN

In [ ]:
precison  =  predicted data pai kitne percent sahi hai
recall = actual data pai kitne percent sahi hai

In [51]:
print(classification_report(y_train, y_train_pred))

              precision    recall  f1-score   support

           0       0.85      0.99      0.92      2327
           1       0.52      0.04      0.07       415

    accuracy                           0.85      2742
   macro avg       0.68      0.52      0.49      2742
weighted avg       0.80      0.85      0.79      2742

In [ ]:
# imbalanced data

In [54]:
data.TenYearCHD.value_counts()

TenYearCHD
0    3099
1     557
Name: count, dtype: int64

In [55]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(sampling_strategy='minority', random_state=42)

In [56]:
X_train_sm, y_train_sm = smote.fit_resample(X_train, y_train)

In [60]:
y_train_sm.value_counts()

TenYearCHD
0    2327
1    2327
Name: count, dtype: int64

In [61]:
lr = LogisticRegression()

In [66]:
lr.fit(X_train_sm, y_train_sm)

LogisticRegression()

In [67]:
print(classification_report(y_train_sm,lr.predict(X_train_sm)))

              precision    recall  f1-score   support

           0       0.66      0.64      0.65      2327
           1       0.65      0.67      0.66      2327

    accuracy                           0.66      4654
   macro avg       0.66      0.66      0.66      4654
weighted avg       0.66      0.66      0.66      4654

In [68]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [69]:
min_max_scaler= MinMaxScaler()

In [74]:
scale_X_train = min_max_scaler.fit_transform(X_train_sm)
scale_X_test = min_max_scaler.transform(X_test)

In [76]:
lr = LogisticRegression()

In [78]:
lr.fit(scale_X_train, y_train_sm)

LogisticRegression()

In [80]:
y_sclae_train = lr.predict(scale_X_train)

In [82]:
print(classification_report(y_train_sm, y_sclae_train))

              precision    recall  f1-score   support

           0       0.70      0.67      0.69      2327
           1       0.69      0.71      0.70      2327

    accuracy                           0.69      4654
   macro avg       0.69      0.69      0.69      4654
weighted avg       0.69      0.69      0.69      4654

In [83]:
from sklearn.svm import SVC

In [ ]:
rbf --- > non linear , miscolinear hon

In [98]:
sv = SVC(kernel= "poly")  #  hyperparameter tunig

In [99]:
sv.fit(scale_X_train, y_train_sm)

SVC(kernel='poly')

In [100]:
sv_X_train_pred = sv.predict(scale_X_train)

In [101]:
print(classification_report(y_train_sm, sv_X_train_pred))

              precision    recall  f1-score   support

           0       0.75      0.77      0.76      2327
           1       0.77      0.74      0.75      2327

    accuracy                           0.76      4654
   macro avg       0.76      0.76      0.76      4654
weighted avg       0.76      0.76      0.76      4654