In [113]:
import pandas as pd

In [114]:
data = pd.read_csv("diabetes.csv")

In [81]:
x= data.drop(["Outcome"],axis = 1)
y= data.Outcome

In [121]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(x,y, test_size=0.23 , random_state=43)

In [122]:
X_train

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
484,0,145,0,0,0,44.2,0.630,31
598,1,173,74,0,0,36.8,0.088,38
410,6,102,90,39,0,35.7,0.674,28
658,11,127,106,0,0,39.0,0.190,51
42,7,106,92,18,0,22.7,0.235,48
...,...,...,...,...,...,...,...,...
527,3,116,74,15,105,26.3,0.107,24
678,3,121,52,0,0,36.0,0.127,25
538,0,127,80,37,210,36.3,0.804,23
213,0,140,65,26,130,42.6,0.431,24
188,8,109,76,39,114,27.9,0.640,31

In [123]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((412, 8), (124, 8), (412,), (124,))

In [115]:
shuffle_data_1=data[data.Outcome==1].sample(268)

In [116]:
shuffle_data_2=data[data.Outcome==0].sample(268)

In [117]:
268+268

536

In [118]:
balanced_data = pd.concat([shuffle_data_1, shuffle_data_2]).sample(536)
balanced_data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
739,1,102,74,0,0,39.5,0.293,42,1
232,1,79,80,25,37,25.4,0.583,22,0
391,5,166,76,0,0,45.7,0.340,27,1
719,5,97,76,27,0,35.6,0.378,52,1
366,6,124,72,0,0,27.6,0.368,29,1

In [119]:
balanced_data.Outcome.value_counts()

Outcome
1    268
0    268
Name: count, dtype: int64

In [120]:
x= balanced_data.drop(["Outcome"],axis = 1)
y= balanced_data.Outcome

In [124]:
import warnings
warnings.filterwarnings("ignore")

In [125]:
from sklearn.linear_model import LogisticRegression

In [126]:
lr  = LogisticRegression()

In [127]:
lr.fit(X_train, y_train)

LogisticRegression()

### Performance Evaluation

In [128]:
from sklearn.metrics import confusion_matrix, recall_score, f1_score, accuracy_score,precision_score, classification_report

In [129]:
y_pred_train =lr.predict(X_train)

In [130]:
pd.DataFrame({"Actual":y_train,  "Predict":y_pred_train})

     Actual  Predict
484       1        1
598       1        1
410       0        1
658       0        1
42        0        0
..      ...      ...
527       0        0
678       1        0
538       0        1
213       1        1
188       1        0

[412 rows x 2 columns]

In [131]:
accuracy_score(y_train, y_pred_train)

0.7135922330097088

In [132]:
confusion_matrix(y_train, y_pred_train)

array([[127,  63],
       [ 55, 167]])

In [ ]:
 model mai jitne 0 the wo bilkul sahi bole 0.79
 model mai jitne 1 the wo bilkul sahi bole 0.72

In [134]:
data.Outcome.value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [ ]:
Imbalanced data

In [ ]:
precison  =  predicted data pai kitne percent sahi hai
recall = actual data pai kitne percent sahi hai

In [138]:
print(classification_report(y_train, y_pred_train))

              precision    recall  f1-score   support

           0       0.70      0.67      0.68       190
           1       0.73      0.75      0.74       222

    accuracy                           0.71       412
   macro avg       0.71      0.71      0.71       412
weighted avg       0.71      0.71      0.71       412